package com.rockstar.o2o.pojo;

// Generated 2015-5-27 15:41:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContentCollect generated by hbm2java
 */
@Entity
@Table(name = "content_collect")
public class ContentCollect implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pkCollect;
	private String collecttype;
	private String collecttime;
	private Long pkContent;
	private String iscollect;
	private String collectfrom;
	private String collectorid;
	private Long pkUser;
	private String ts;
	private Short dr;

	public ContentCollect() {
	}

	public ContentCollect(String collecttype, String collecttime,
			Long pkContent, String iscollect, String collectfrom,
			String collectorid, Long pkUser, String ts, Short dr) {
		this.collecttype = collecttype;
		this.collecttime = collecttime;
		this.pkContent = pkContent;
		this.iscollect = iscollect;
		this.collectfrom = collectfrom;
		this.collectorid = collectorid;
		this.pkUser = pkUser;
		this.ts = ts;
		this.dr = dr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pk_collect", unique = true, nullable = false)
	public Long getPkCollect() {
		return this.pkCollect;
	}

	public void setPkCollect(Long pkCollect) {
		this.pkCollect = pkCollect;
	}

	@Column(name = "collecttype", length = 30)
	public String getCollecttype() {
		return this.collecttype;
	}

	public void setCollecttype(String collecttype) {
		this.collecttype = collecttype;
	}

	@Column(name = "collecttime", length = 19)
	public String getCollecttime() {
		return this.collecttime;
	}

	public void setCollecttime(String collecttime) {
		this.collecttime = collecttime;
	}

	@Column(name = "pk_content")
	public Long getPkContent() {
		return this.pkContent;
	}

	public void setPkContent(Long pkContent) {
		this.pkContent = pkContent;
	}

	@Column(name = "iscollect", length = 1)
	public String getIscollect() {
		return this.iscollect;
	}

	public void setIscollect(String iscollect) {
		this.iscollect = iscollect;
	}

	@Column(name = "collectfrom", length = 30)
	public String getCollectfrom() {
		return this.collectfrom;
	}

	public void setCollectfrom(String collectfrom) {
		this.collectfrom = collectfrom;
	}

	@Column(name = "collectorid")
	public String getCollectorid() {
		return this.collectorid;
	}

	public void setCollectorid(String collectorid) {
		this.collectorid = collectorid;
	}

	@Column(name = "pkUser")
	public Long getPkUser() {
		return this.pkUser;
	}

	public void setPkUser(Long pkUser) {
		this.pkUser = pkUser;
	}

	@Column(name = "ts", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "dr")
	public Short getDr() {
		return this.dr;
	}

	public void setDr(Short dr) {
		this.dr = dr;
	}

}
