package com.rockstar.o2o.pojo;

// Generated 2015-6-4 13:32:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MessageSendRecord generated by hbm2java
 */
@Entity
@Table(name = "message_send_record")
public class MessageSendRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long pkRecord;
	private Long pkMember;
	private Long pkGroup;
	private String groupname;
	private String membername;
	private String messagegroup;
	private String messagetype;
	private String content;
	private Long pkSender;
	private String sendfrom;
	private String sendtime;
	private String recordstatus;
	private String sendresult;
	private String cellphone;
	private String ts;
	private Short dr;

	public MessageSendRecord() {
	}

	public MessageSendRecord(long pkRecord) {
		this.pkRecord = pkRecord;
	}

	public MessageSendRecord(long pkRecord, Long pkMember, Long pkGroup,
			String groupname, String membername, String messagegroup,
			String messagetype, String content, Long pkSender, String sendfrom,
			String sendtime, String recordstatus, String sendresult,String cellphone, String ts,
			Short dr) {
		this.pkRecord = pkRecord;
		this.pkMember = pkMember;
		this.pkGroup = pkGroup;
		this.groupname = groupname;
		this.membername = membername;
		this.messagegroup = messagegroup;
		this.messagetype = messagetype;
		this.content = content;
		this.pkSender = pkSender;
		this.sendfrom = sendfrom;
		this.sendtime = sendtime;
		this.recordstatus = recordstatus;
		this.sendresult = sendresult;
		this.cellphone = cellphone;
		this.ts = ts;
		this.dr = dr;
	}

	@Id
	@GeneratedValue
	@Column(name = "pk_record", unique = true, nullable = false)
	public long getPkRecord() {
		return this.pkRecord;
	}

	public void setPkRecord(long pkRecord) {
		this.pkRecord = pkRecord;
	}

	@Column(name = "pk_member")
	public Long getPkMember() {
		return this.pkMember;
	}

	public void setPkMember(Long pkMember) {
		this.pkMember = pkMember;
	}

	@Column(name = "pk_group")
	public Long getPkGroup() {
		return this.pkGroup;
	}

	public void setPkGroup(Long pkGroup) {
		this.pkGroup = pkGroup;
	}

	@Column(name = "groupname", length = 100)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "membername", length = 100)
	public String getMembername() {
		return this.membername;
	}

	public void setMembername(String membername) {
		this.membername = membername;
	}

	@Column(name = "messagegroup", length = 30)
	public String getMessagegroup() {
		return this.messagegroup;
	}

	public void setMessagegroup(String messagegroup) {
		this.messagegroup = messagegroup;
	}

	@Column(name = "messagetype")
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "pk_sender")
	public Long getPkSender() {
		return this.pkSender;
	}

	public void setPkSender(Long pkSender) {
		this.pkSender = pkSender;
	}

	@Column(name = "sendfrom", length = 50)
	public String getSendfrom() {
		return this.sendfrom;
	}

	public void setSendfrom(String sendfrom) {
		this.sendfrom = sendfrom;
	}

	@Column(name = "sendtime", length = 19)
	public String getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	@Column(name = "recordstatus", length = 20)
	public String getRecordstatus() {
		return this.recordstatus;
	}

	public void setRecordstatus(String recordstatus) {
		this.recordstatus = recordstatus;
	}

	@Column(name = "sendresult", length = 10)
	public String getSendresult() {
		return this.sendresult;
	}

	public void setSendresult(String sendresult) {
		this.sendresult = sendresult;
	}

	
	@Column(name = "cellphone")
	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "ts", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "dr")
	public Short getDr() {
		return this.dr;
	}

	public void setDr(Short dr) {
		this.dr = dr;
	}

}
