package com.rockstar.o2o.pojo;

// Generated 2015-6-4 11:44:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MessageGroup generated by hbm2java
 */
@Entity
@Table(name = "message_group")
public class MessageGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long pkGroup;
	private String groupname;
	private Integer groupnum;
	private String groupfrom;
	private String ts;
	private Short dr;
	private Long creatorid;
	private String createtime;

	public MessageGroup() {
	}

	public MessageGroup(long pkGroup) {
		this.pkGroup = pkGroup;
	}

	public MessageGroup(long pkGroup, String groupname, Integer groupnum,
			String groupfrom, String ts, Short dr, Long creatorid,
			String createtime) {
		this.pkGroup = pkGroup;
		this.groupname = groupname;
		this.groupnum = groupnum;
		this.groupfrom = groupfrom;
		this.ts = ts;
		this.dr = dr;
		this.creatorid = creatorid;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue
	@Column(name = "pk_group", unique = true, nullable = false)
	public long getPkGroup() {
		return this.pkGroup;
	}

	public void setPkGroup(long pkGroup) {
		this.pkGroup = pkGroup;
	}

	@Column(name = "groupname", length = 100)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "groupnum")
	public Integer getGroupnum() {
		return this.groupnum;
	}

	public void setGroupnum(Integer groupnum) {
		this.groupnum = groupnum;
	}

	@Column(name = "groupfrom", length = 50)
	public String getGroupfrom() {
		return this.groupfrom;
	}

	public void setGroupfrom(String groupfrom) {
		this.groupfrom = groupfrom;
	}

	@Column(name = "ts", length = 19)
	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	@Column(name = "dr")
	public Short getDr() {
		return this.dr;
	}

	public void setDr(Short dr) {
		this.dr = dr;
	}

	@Column(name = "creatorid")
	public Long getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(Long creatorid) {
		this.creatorid = creatorid;
	}

	@Column(name = "createtime", length = 19)
	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

}
